/*
 * Author: Oyelowo Oyedayo
 * Email: oyelowo.oss@gmail.com
 * Copyright (c) 2023 Oyelowo Oyedayo
 * Licensed under the MIT license
 */
pub const SIGNABLES: [&str; 40] = [
    "m",
    "mt",
    "mr",
    "mb",
    "ml",
    "mx",
    "my",
    "mb",
    "ml",
    "mr",
    "mt",
    "mx",
    "my",
    "p",
    "pb",
    "pl",
    "pr",
    "pt",
    "px",
    "py",
    "space-x",
    "space-y",
    "translate-x",
    "translate-y",
    "inset",
    "inset-y",
    "inset-x",
    "top",
    "right",
    "bottom",
    "left",
    "gap",
    "gap-x",
    "gap-y",
    "divide-x",
    "divide-y",
    "grid-auto-rows",
    "grid-auto-columns",
    "z",
    "order",
    // "scroll-mx",
    // "scroll-my",
    // "scroll-m",
];
