/*
 * Author: Oyelowo Oyedayo
 * Email: oyelowo.oss@gmail.com
 * Copyright (c) 2023 Oyelowo Oyedayo
 * Licensed under the MIT license
 */
use serde::{Deserialize, Serialize};
use std::collections::HashMap;

#[derive(Serialize, Deserialize, Default, Debug)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct TailwindConfig {
    pub theme: Theme,
    pub allowed_lists: Option<AllowedLists>,
    pub variants: Variants,
    pub core_plugins: CorePlugins,
    pub plugins: Plugins,
}

#[derive(Serialize, Deserialize, Default, Debug)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct CorePlugins {
    pub screens: bool,
    pub colors: bool,
    pub spacing: bool,

    pub width: bool,
    pub height: bool,

    pub min_width: bool,

    pub min_height: bool,

    pub max_width: bool,

    pub max_height: bool,

    pub padding: bool,
    pub margin: bool,
    pub negative_margin: bool,

    pub shadows: bool,

    pub z_index: bool,
    pub opacity: bool,
    pub stroke: bool,

    pub accent_color: bool,
    pub accessibility: bool,

    pub align_content: bool,
    pub align_items: bool,
    pub align_self: bool,
    pub animation: bool,
    pub appearance: bool,
    pub aspect_ratio: bool,
    pub grayscale: bool,
    pub backdrop_blur: bool,
    pub backdrop_brightness: bool,
    pub backdrop_contrast: bool,
    pub backdrop_filter: bool,
    pub backdrop_grayscale: bool,
    pub backdrop_hue_rotate: bool,
    pub backdrop_invert: bool,
    pub backdrop_opacity: bool,
    pub backdrop_saturate: bool,
    pub backdrop_sepia: bool,
    pub background_attachment: bool,
    pub background_blend_mode: bool,
    pub background_clip: bool,
    pub background_color: bool,
    pub background_image: bool,
    pub background_opacity: bool,
    pub background_origin: bool,
    pub background_position: bool,
    pub background_repeat: bool,
    pub background_size: bool,
    pub blur: bool,
    pub border_collapse: bool,
    pub border_color: bool,
    pub border_opacity: bool,
    pub border_radius: bool,
    pub border_spacing: bool,
    pub border_style: bool,
    pub border_width: bool,
    pub box_decoration_break: bool,
    pub box_shadow: bool,
    pub box_shadow_color: bool,
    pub box_sizing: bool,
    pub break_after: bool,
    pub break_before: bool,
    pub break_inside: bool,
    pub brightness: bool,
    pub caption_side: bool,
    pub caret_color: bool,
    pub clear: bool,
    pub columns: bool,
    pub container: bool,
    pub content: bool,
    pub contrast: bool,
    pub cursor: bool,
    pub display: bool,
    pub divide_color: bool,
    pub divide_opacity: bool,
    pub divide_style: bool,
    pub divide_width: bool,
    pub drop_shadow: bool,
    pub fill: bool,
    pub filter: bool,
    pub flex: bool,
    pub flex_basis: bool,
    pub flex_direction: bool,
    pub flex_grow: bool,
    pub flex_shrink: bool,
    pub flex_wrap: bool,
    pub float: bool,
    pub font_family: bool,
    pub font_size: bool,
    pub font_smoothing: bool,
    pub font_style: bool,
    pub font_variant_numeric: bool,
    pub font_weight: bool,
    pub gap: bool,
    pub gradient_color_stops: bool,
    pub grid_auto_columns: bool,
    pub grid_auto_flow: bool,
    pub grid_auto_rows: bool,
    pub grid_column: bool,
    pub grid_column_end: bool,
    pub grid_column_start: bool,
    pub grid_row: bool,
    pub grid_row_end: bool,
    pub grid_row_start: bool,
    pub grid_template_columns: bool,
    pub grid_template_rows: bool,
    pub hue_rotate: bool,
    pub hyphens: bool,
    pub top: bool,
    pub right: bool,
    pub left: bool,
    pub bottom: bool,
    pub start: bool,
    pub end: bool,
    pub inset: bool,
    pub invert: bool,
    pub isolation: bool,
    pub justify_content: bool,
    pub justify_items: bool,
    pub justify_self: bool,
    pub letter_spacing: bool,
    pub line_clamp: bool,
    pub line_height: bool,
    pub list_style_image: bool,
    pub list_style_position: bool,
    pub list_style_type: bool,
    pub mix_blend_mode: bool,
    pub object_fit: bool,
    pub object_position: bool,
    pub order: bool,
    pub outline_color: bool,
    pub outline_offset: bool,
    pub outline_style: bool,
    pub outline_width: bool,
    pub overflow: bool,
    pub overscroll_behavior: bool,
    pub place_content: bool,
    pub place_items: bool,
    pub place_self: bool,
    pub placeholder_color: bool,
    pub placeholder_opacity: bool,
    pub pointer_events: bool,
    pub position: bool,
    pub preflight: bool,
    pub resize: bool,
    pub ring_color: bool,
    pub ring_offset_color: bool,
    pub ring_offset_width: bool,
    pub ring_opacity: bool,
    pub ring_width: bool,
    pub rotate: bool,
    pub saturate: bool,
    pub scale: bool,
    pub scroll_behavior: bool,
    pub scroll_margin: bool,
    pub scroll_padding: bool,
    pub scroll_snap_align: bool,
    pub scroll_snap_stop: bool,
    pub scroll_snap_type: bool,
    pub sepia: bool,
    pub skew: bool,
    pub space: bool,
    pub stroke_width: bool,
    pub table_layout: bool,
    pub text_align: bool,
    pub text_color: bool,
    pub text_decoration: bool,
    pub text_decoration_color: bool,
    pub text_decoration_style: bool,
    pub text_decoration_thickness: bool,
    pub text_indent: bool,
    pub text_opacity: bool,
    pub text_overflow: bool,
    pub text_transform: bool,
    pub text_underline_offset: bool,
    pub touch_action: bool,
    pub transform: bool,
    pub transform_origin: bool,

    pub transition_delay: bool,
    pub transition_duration: bool,
    pub transition_property: bool,
    pub transition_timing_function: bool,
    pub translate: bool,
    pub user_select: bool,
    pub vertical_align: bool,
    pub visibility: bool,
    pub whitespace: bool,
    pub will_change: bool,
    pub word_break: bool,
    pub screen_readers: bool,
    // pub extend: HashMap<Key, HashMap<String, String>>,
}

#[derive(Serialize, Deserialize, Default, Debug)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct AllowedLists {
    pub classes: Option<Vec<String>>,
    pub modifiers: Option<Vec<String>>,
}

#[derive(Serialize, Deserialize, Default, Debug)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct Theme {
    #[serde(flatten)]
    pub overrides: CustomisableClasses,
    pub extend: CustomisableClasses,
}

// Represents a color which can either be a simple string or a nested structure.
#[derive(Debug, Serialize, Deserialize, PartialEq, Clone)]
#[serde(untagged)]
pub enum ColorValue {
    Simple(String),
    Shades(HashMap<String, String>),
}

// #[derive(Debug, Deserialize)]
// struct Theme {
//     colors: Option<HashMap<String, ColorValue>>,
// }

#[derive(Debug, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ScreenValue {
    Simple(String),
    Range(RangeBreakpoint),
    MultiRange(Vec<RangeBreakpoint>),
    Raw(RawBreakpoint),
}

#[derive(Debug, Serialize, Deserialize)]
pub struct RangeBreakpoint {
    #[serde(skip_serializing_if = "Option::is_none")]
    min: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    max: Option<String>,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct RawBreakpoint {
    raw: String,
}

pub type Key = String;

#[derive(Serialize, Deserialize, Default, Debug)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct CustomisableClasses {
    // pub screens: Option<HashMap<String, String>>,
    pub screens: Option<HashMap<Key, ScreenValue>>,
    pub colors: Option<HashMap<Key, ColorValue>>,
    pub spacing: Option<HashMap<Key, String>>,

    pub width: Option<HashMap<Key, String>>,
    pub height: Option<HashMap<Key, String>>,

    pub min_width: Option<HashMap<Key, String>>,

    pub min_height: Option<HashMap<Key, String>>,

    pub max_width: Option<HashMap<Key, String>>,

    pub max_height: Option<HashMap<Key, String>>,

    pub padding: Option<HashMap<Key, String>>,
    pub margin: Option<HashMap<Key, String>>,
    pub negative_margin: Option<HashMap<Key, String>>,

    pub shadows: Option<HashMap<Key, String>>,

    pub z_index: Option<HashMap<Key, String>>,
    pub opacity: Option<HashMap<Key, String>>,
    pub stroke: Option<HashMap<Key, ColorValue>>,

    pub accent_color: Option<HashMap<Key, ColorValue>>,
    pub accessibility: Option<HashMap<Key, String>>,

    pub align_content: Option<HashMap<Key, String>>,
    pub align_items: Option<HashMap<Key, String>>,
    pub align_self: Option<HashMap<Key, String>>,
    pub animation: Option<HashMap<Key, String>>,
    pub appearance: Option<HashMap<Key, String>>,
    pub aspect_ratio: Option<HashMap<Key, String>>,
    pub grayscale: Option<HashMap<Key, String>>,
    pub backdrop_blur: Option<HashMap<Key, String>>,
    pub backdrop_brightness: Option<HashMap<Key, String>>,
    pub backdrop_contrast: Option<HashMap<Key, String>>,
    pub backdrop_filter: Option<HashMap<Key, String>>,
    pub backdrop_grayscale: Option<HashMap<Key, String>>,
    pub backdrop_hue_rotate: Option<HashMap<Key, String>>,
    pub backdrop_invert: Option<HashMap<Key, String>>,
    pub backdrop_opacity: Option<HashMap<Key, String>>,
    pub backdrop_saturate: Option<HashMap<Key, String>>,
    pub backdrop_sepia: Option<HashMap<Key, String>>,
    pub background_attachment: Option<HashMap<Key, String>>,
    pub background_blend_mode: Option<HashMap<Key, String>>,
    pub background_clip: Option<HashMap<Key, String>>,
    pub background_color: Option<HashMap<Key, ColorValue>>,
    pub background_image: Option<HashMap<Key, String>>,
    pub background_opacity: Option<HashMap<Key, String>>,
    pub background_origin: Option<HashMap<Key, String>>,
    pub background_position: Option<HashMap<Key, String>>,
    pub background_repeat: Option<HashMap<Key, String>>,
    pub background_size: Option<HashMap<Key, String>>,
    pub blur: Option<HashMap<Key, String>>,
    pub border_collapse: Option<HashMap<Key, String>>,
    pub border_color: Option<HashMap<Key, ColorValue>>,
    pub border_opacity: Option<HashMap<Key, String>>,
    pub border_radius: Option<HashMap<Key, String>>,
    pub border_spacing: Option<HashMap<Key, String>>,
    pub border_style: Option<HashMap<Key, String>>,
    pub border_width: Option<HashMap<Key, String>>,
    pub box_decoration_break: Option<HashMap<Key, String>>,
    pub box_shadow: Option<HashMap<Key, String>>,
    pub box_shadow_color: Option<HashMap<Key, ColorValue>>,
    pub box_sizing: Option<HashMap<Key, String>>,
    pub break_after: Option<HashMap<Key, String>>,
    pub break_before: Option<HashMap<Key, String>>,
    pub break_inside: Option<HashMap<Key, String>>,
    pub brightness: Option<HashMap<Key, String>>,
    pub caption_side: Option<HashMap<Key, String>>,
    pub caret_color: Option<HashMap<Key, ColorValue>>,
    pub clear: Option<HashMap<Key, String>>,
    pub columns: Option<HashMap<Key, String>>,
    pub container: Option<HashMap<Key, String>>,
    pub content: Option<HashMap<Key, String>>,
    pub contrast: Option<HashMap<Key, String>>,
    pub cursor: Option<HashMap<Key, String>>,
    pub display: Option<HashMap<Key, String>>,
    pub divide_color: Option<HashMap<Key, ColorValue>>,
    pub divide_opacity: Option<HashMap<Key, String>>,
    pub divide_style: Option<HashMap<Key, String>>,
    pub divide_width: Option<HashMap<Key, String>>,
    pub drop_shadow: Option<HashMap<Key, String>>,
    pub fill: Option<HashMap<Key, ColorValue>>,
    pub filter: Option<HashMap<Key, String>>,
    pub flex: Option<HashMap<Key, String>>,
    pub flex_basis: Option<HashMap<Key, String>>,
    pub flex_direction: Option<HashMap<Key, String>>,
    pub flex_grow: Option<HashMap<Key, String>>,
    pub flex_shrink: Option<HashMap<Key, String>>,
    pub flex_wrap: Option<HashMap<Key, String>>,
    pub float: Option<HashMap<Key, String>>,
    pub font_family: Option<HashMap<Key, String>>,
    pub font_size: Option<HashMap<Key, String>>,
    pub font_smoothing: Option<HashMap<Key, String>>,
    pub font_style: Option<HashMap<Key, String>>,
    pub font_variant_numeric: Option<HashMap<Key, String>>,
    pub font_weight: Option<HashMap<Key, String>>,
    pub gap: Option<HashMap<Key, String>>,
    pub gradient_color_stops: Option<HashMap<Key, ColorValue>>,
    pub grid_auto_columns: Option<HashMap<Key, String>>,
    pub grid_auto_flow: Option<HashMap<Key, String>>,
    pub grid_auto_rows: Option<HashMap<Key, String>>,
    pub grid_column: Option<HashMap<Key, String>>,
    pub grid_column_end: Option<HashMap<Key, String>>,
    pub grid_column_start: Option<HashMap<Key, String>>,
    pub grid_row: Option<HashMap<Key, String>>,
    pub grid_row_end: Option<HashMap<Key, String>>,
    pub grid_row_start: Option<HashMap<Key, String>>,
    pub grid_template_columns: Option<HashMap<Key, String>>,
    pub grid_template_rows: Option<HashMap<Key, String>>,
    pub hue_rotate: Option<HashMap<Key, String>>,
    pub hyphens: Option<HashMap<Key, String>>,
    pub top: Option<HashMap<Key, String>>,
    pub right: Option<HashMap<Key, String>>,
    pub left: Option<HashMap<Key, String>>,
    pub bottom: Option<HashMap<Key, String>>,
    pub start: Option<HashMap<Key, String>>,
    pub end: Option<HashMap<Key, String>>,
    pub inset: Option<HashMap<Key, String>>,
    pub invert: Option<HashMap<Key, String>>,
    pub isolation: Option<HashMap<Key, String>>,
    pub justify_content: Option<HashMap<Key, String>>,
    pub justify_items: Option<HashMap<Key, String>>,
    pub justify_self: Option<HashMap<Key, String>>,
    pub letter_spacing: Option<HashMap<Key, String>>,
    pub line_clamp: Option<HashMap<Key, String>>,
    pub line_height: Option<HashMap<Key, String>>,
    pub list_style_image: Option<HashMap<Key, String>>,
    pub list_style_position: Option<HashMap<Key, String>>,
    pub list_style_type: Option<HashMap<Key, String>>,
    pub mix_blend_mode: Option<HashMap<Key, String>>,
    pub object_fit: Option<HashMap<Key, String>>,
    pub object_position: Option<HashMap<Key, String>>,
    pub order: Option<HashMap<Key, String>>,
    pub outline_color: Option<HashMap<Key, ColorValue>>,
    pub outline_offset: Option<HashMap<Key, String>>,
    pub outline_style: Option<HashMap<Key, String>>,
    pub outline_width: Option<HashMap<Key, String>>,
    pub overflow: Option<HashMap<Key, String>>,
    pub overscroll_behavior: Option<HashMap<Key, String>>,
    pub place_content: Option<HashMap<Key, String>>,
    pub place_items: Option<HashMap<Key, String>>,
    pub place_self: Option<HashMap<Key, String>>,
    pub placeholder_color: Option<HashMap<Key, ColorValue>>,
    pub placeholder_opacity: Option<HashMap<Key, String>>,
    pub pointer_events: Option<HashMap<Key, String>>,
    pub position: Option<HashMap<Key, String>>,
    pub preflight: Option<HashMap<Key, String>>,
    pub resize: Option<HashMap<Key, String>>,
    pub ring_color: Option<HashMap<Key, ColorValue>>,
    pub ring_offset_color: Option<HashMap<Key, ColorValue>>,
    pub ring_offset_width: Option<HashMap<Key, String>>,
    pub ring_opacity: Option<HashMap<Key, String>>,
    pub ring_width: Option<HashMap<Key, String>>,
    pub rotate: Option<HashMap<Key, String>>,
    pub saturate: Option<HashMap<Key, String>>,
    pub scale: Option<HashMap<Key, String>>,
    pub scroll_behavior: Option<HashMap<Key, String>>,
    pub scroll_margin: Option<HashMap<Key, String>>,
    pub scroll_padding: Option<HashMap<Key, String>>,
    pub scroll_snap_align: Option<HashMap<Key, String>>,
    pub scroll_snap_stop: Option<HashMap<Key, String>>,
    pub scroll_snap_type: Option<HashMap<Key, String>>,
    pub sepia: Option<HashMap<Key, String>>,
    pub skew: Option<HashMap<Key, String>>,
    pub space: Option<HashMap<Key, String>>,
    pub stroke_width: Option<HashMap<Key, String>>,
    pub table_layout: Option<HashMap<Key, String>>,
    pub text_align: Option<HashMap<Key, String>>,
    pub text_color: Option<HashMap<Key, ColorValue>>,
    pub text_decoration: Option<HashMap<Key, String>>,
    pub text_decoration_color: Option<HashMap<Key, ColorValue>>,
    pub text_decoration_style: Option<HashMap<Key, String>>,
    pub text_decoration_thickness: Option<HashMap<Key, String>>,
    pub text_indent: Option<HashMap<Key, String>>,
    pub text_opacity: Option<HashMap<Key, String>>,
    pub text_overflow: Option<HashMap<Key, String>>,
    pub text_transform: Option<HashMap<Key, String>>,
    pub text_underline_offset: Option<HashMap<Key, String>>,
    pub touch_action: Option<HashMap<Key, String>>,
    pub transform: Option<HashMap<Key, String>>,
    pub transform_origin: Option<HashMap<Key, String>>,

    pub transition_delay: Option<HashMap<Key, String>>,
    pub transition_duration: Option<HashMap<Key, String>>,
    pub transition_property: Option<HashMap<Key, String>>,
    pub transition_timing_function: Option<HashMap<Key, String>>,
    pub translate: Option<HashMap<Key, String>>,
    pub user_select: Option<HashMap<Key, String>>,
    pub vertical_align: Option<HashMap<Key, String>>,
    pub visibility: Option<HashMap<Key, String>>,
    pub whitespace: Option<HashMap<Key, String>>,
    pub will_change: Option<HashMap<Key, String>>,
    pub word_break: Option<HashMap<Key, String>>,

    pub screen_readers: Option<HashMap<Key, String>>,
    // pub extend: HashMap<Key, HashMap<String, String>>,
}

// #[derive(Serialize, Deserialize, Debug)]
// pub struct Extend {
//     pub screens: Option<HashMap<Key, String>>,
//     // add other fields as needed
// }

#[derive(Serialize, Deserialize, Default, Debug)]
pub struct Variants {}

#[derive(Serialize, Deserialize, Default, Debug)]
pub struct Plugins {}
